name: Validate changes
on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout service
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run gradle tests
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
          arguments: check

  #Todo: Auto merge is running soon after the validation
  #Todo: It should run after the manual code review
  automerge:
    runs-on: ubuntu-latest
    needs:
      - validate
    steps:
      - name: Merge changes to trunk
        uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{  }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
